### ISSUE TITLE
Do a new release to be compatible with PyPy

### ISSUE THREAD

**Issue by antocuni** [gevent/gevent#1408]
The latest releases gevent doesn't work with the latest version of PyPy (7.1.1); `genvet.monkey.patch_all()` raises:
```
AttributeError: 'thread.RLock' object has no attribute '_RLock__owner'
```

This has already been fixed by d0e0465891e30abb3e64c25324268251ad5c994c. Would it be possible to have an official gevent release which includes the fix?

**Comment by jamadden** [comment]
1.5a1 is in PyPI.
