### ISSUE TITLE
Compatibility with Python 3.11 and greenlet 2.0.0

### ISSUE THREAD

**Issue by hrnciar** [gevent/gevent#1867]
* gevent version: 21.12.0 using Fedora's RPM package
* greenlet version: 2.0.0a1
* Python version: 3.11.0a5
* Cython version: 3.0.0a10
* Operating System: Fedora Rawhide

### Description:

In Fedora, we are doing rebuilds of all Python packages with development versions of Python 3.11, currently 5th alpha. 
Python 3.11 brings some backwards-incompatible changes that affect greenlet. Greenlet developers have already fixed some issues and greenlet 2.0.0a1 builds with Python 3.11. When I tried to build gevent in this setup I've got this error:

~~~~
src/gevent/greenlet.c: In function â€˜__pyx_f_6gevent_17_gevent_cgreenlet__extract_stackâ€™:
src/gevent/greenlet.c:6218:43: error: â€˜PyFrameObjectâ€™ {aka â€˜struct _frameâ€™} has no member named â€˜f_codeâ€™
 6218 |     __pyx_t_6 = ((PyObject *)__pyx_v_frame->f_code);
      |                                           ^~
src/gevent/greenlet.c: In function â€˜__pyx_f_6gevent_17_gevent_cgreenlet_get_generic_parentâ€™:
src/gevent/greenlet.c:19924:26: error: â€˜PyGreenletâ€™ {aka â€˜struct _greenletâ€™} has no member named â€˜parentâ€™
19924 |   __pyx_t_1 = ((__pyx_v_s->parent != NULL) != 0);
      |                          ^~
In file included from /usr/include/python3.11/Python.h:42,
                 from src/gevent/greenlet.c:37:
src/gevent/greenlet.c:19935:40: error: â€˜PyGreenletâ€™ {aka â€˜struct _greenletâ€™} has no member named â€˜parentâ€™
19935 |     __Pyx_INCREF(((PyObject *)__pyx_v_s->parent));
      |                                        ^~
/usr/include/python3.11/object.h:112:41: note: in definition of macro â€˜_PyObject_CASTâ€™
  112 | #define _PyObject_CAST(op) ((PyObject*)(op))
      |                                         ^~
./src/gevent/_generated_include/Refnanny_proto_251246e7dae1dc172351bab7073efbf5de224e2b.h:50:27: note: in expansion of macro â€˜Py_INCREFâ€™
   50 |   #define __Pyx_INCREF(r) Py_INCREF(r)
      |                           ^~~~~~~~~
src/gevent/greenlet.c:19935:5: note: in expansion of macro â€˜__Pyx_INCREFâ€™
19935 |     __Pyx_INCREF(((PyObject *)__pyx_v_s->parent));
      |     ^~~~~~~~~~~~
src/gevent/greenlet.c:19936:37: error: â€˜PyGreenletâ€™ {aka â€˜struct _greenletâ€™} has no member named â€˜parentâ€™
19936 |     __pyx_r = ((PyObject *)__pyx_v_s->parent);
      |                                     ^~
src/gevent/greenlet.c: In function â€˜__pyx_f_6gevent_17_gevent_cgreenlet_get_my_hubâ€™:
src/gevent/greenlet.c:19988:26: error: â€˜PyGreenletâ€™ {aka â€˜struct _greenletâ€™} has no member named â€˜parentâ€™
19988 |   __pyx_t_1 = ((__pyx_v_s->parent != NULL) != 0);
      |                          ^~
src/gevent/greenlet.c:19999:42: error: â€˜PyGreenletâ€™ {aka â€˜struct _greenletâ€™} has no member named â€˜parentâ€™
19999 |     if (!(likely(((((PyObject *)__pyx_v_s->parent)) == Py_None) || likely(__Pyx_TypeTest(((PyObject *)__pyx_v_s->parent), __pyx_ptype_6gevent_29_gevent_c_greenlet_primitives_SwitchOutGreenletWithLoop))))) __PYX_ERR(1, 45, __pyx_L1_error)
      |                                          ^~
src/gevent/greenlet.c:1156:43: note: in definition of macro â€˜likelyâ€™
 1156 |   #define likely(x)   __builtin_expect(!!(x), 1)
      |                                           ^
src/gevent/greenlet.c:19999:112: error: â€˜PyGreenletâ€™ {aka â€˜struct _greenletâ€™} has no member named â€˜parentâ€™
19999 |     if (!(likely(((((PyObject *)__pyx_v_s->parent)) == Py_None) || likely(__Pyx_TypeTest(((PyObject *)__pyx_v_s->parent), __pyx_ptype_6gevent_29_gevent_c_greenlet_primitives_SwitchOutGreenletWithLoop))))) __PYX_ERR(1, 45, __pyx_L1_error)
      |                                                                                                                ^~
src/gevent/greenlet.c:1156:43: note: in definition of macro â€˜likelyâ€™
 1156 |   #define likely(x)   __builtin_expect(!!(x), 1)
      |                                           ^
src/gevent/greenlet.c:19999:68: note: in expansion of macro â€˜likelyâ€™
19999 |     if (!(likely(((((PyObject *)__pyx_v_s->parent)) == Py_None) || likely(__Pyx_TypeTest(((PyObject *)__pyx_v_s->parent), __pyx_ptype_6gevent_29_gevent_c_greenlet_primitives_SwitchOutGreenletWithLoop))))) __PYX_ERR(1, 45, __pyx_L1_error)
      |                                                                    ^~~~~~
src/gevent/greenlet.c:20000:40: error: â€˜PyGreenletâ€™ {aka â€˜struct _greenletâ€™} has no member named â€˜parentâ€™
20000 |     __Pyx_INCREF(((PyObject *)__pyx_v_s->parent));
      |                                        ^~
/usr/include/python3.11/object.h:112:41: note: in definition of macro â€˜_PyObject_CASTâ€™
  112 | #define _PyObject_CAST(op) ((PyObject*)(op))
      |                                         ^~
./src/gevent/_generated_include/Refnanny_proto_251246e7dae1dc172351bab7073efbf5de224e2b.h:50:27: note: in expansion of macro â€˜Py_INCREFâ€™
   50 |   #define __Pyx_INCREF(r) Py_INCREF(r)
      |                           ^~~~~~~~~
src/gevent/greenlet.c:20000:5: note: in expansion of macro â€˜__Pyx_INCREFâ€™
20000 |     __Pyx_INCREF(((PyObject *)__pyx_v_s->parent));
      |     ^~~~~~~~~~~~
src/gevent/greenlet.c:20001:124: error: â€˜PyGreenletâ€™ {aka â€˜struct _greenletâ€™} has no member named â€˜parentâ€™
20001 |     __pyx_r = ((struct __pyx_obj_6gevent_29_gevent_c_greenlet_primitives_SwitchOutGreenletWithLoop *)((PyObject *)__pyx_v_s->parent));
      |                                                                                                                            ^~
~~~~
You can see full log here https://download.copr.fedorainfracloud.org/results/@python/python3.11/fedora-rawhide-x86_64/03415430-python-gevent/builder-live.log.gz .

I am not well oriented in greenlet/gevent relationship, but I think that greenlet changed some internals and gevent needs to be adapted. 
Plenty of packages depends on gevent and we cannot test them with Python 3.11 without this dependency. I would like to kindly ask for help how to fix gevent. I understand that it is just 1st alpha of greenlet and it can change in the future, but for now, some dirty patch would be sufficient, just to unblock gevent. Thank you.

**Comment by vstinner** [comment]
> src/gevent/greenlet.c:6218:43: error: â€˜PyFrameObjectâ€™ {aka â€˜struct _frameâ€™} has no member named â€˜f_codeâ€™

This file comes from greenlet, not gevent, no?

**Comment by frenzymadness** [comment]
The file `src/gevent/greenlet.c` seems to be generated by Cython as defined in https://github.com/gevent/gevent/blob/5858d226045f701deb8e4b49c03db4cab63053d6/setup.py#L74-L83

From a brief look, it seems to me that the alpha version 3.0.0a of Cython might be the problem here. @vstinner what do you think? Does Cython generate code incompatible with Python 3.11a5?

**Comment by vstinner** [comment]
Oh right, the problem comes from the ``_extract_stack()`` function of src/gevent/greenlet.py. It uses the following code from src/gevent/_gevent_cgreenlet.pxd:

```
cdef extern from "frameobject.h":

    ctypedef class types.FrameType [object PyFrameObject]:
        cdef CodeType f_code
        # Accessing the f_lineno directly doesn't work. There is an accessor
        # function, PyFrame_GetLineNumber that is needed to turn the raw line number
        # into the executing line number.
        # cdef int f_lineno
        # We can't declare this in the object as an object, because it's
        # allowed to be NULL, and Cython can't handle that.
        # We have to go through the python machinery to get a
        # proper None instead, or use an inline function.
        cdef void* f_back

    int PyFrame_GetLineNumber(FrameType frame)
```

The ``PyFrameObject.f_code`` member is accessed directly, whereas it has been removed in Python 3.11. ``PyFrame_GetCode()`` must not be called (function added to Python 3.9).

The problem is also that the ``_extract_stack()`` function not only **gets** f_code member but also **sets** the f_code member:

```
older_Frame.f_code = frame.f_code
```

One option would be to access PyFrameObject.f_frame.f_code, but the f_frame type (``InterpreterFrame``) is only part of the **internal** C API should not be used.

**Comment by vstinner** [comment]
The PyFrameObject.f_code member has been removed by https://github.com/python/cpython/commit/b11a951f16f0603d98de24fee5c023df83ea552c : see https://bugs.python.org/issue44032

See also "[C API] Add getter functions for PyFrameObject and maybe move PyFrameObject to the internal C API": https://bugs.python.org/issue40421

**Comment by vstinner** [comment]
Update:

* I documented PyFrameObject structure changes in What's New in Python 3.11: https://docs.python.org/dev/whatsnew/3.11.html#c-api-changes
* I moved the PyFrameObject structure to the internal C API: https://bugs.python.org/issue46836
* I proposed a PR to make gevent compatible with Python 3.11: https://github.com/gevent/gevent/pull/1872

**Comment by jamadden** [comment]
gevent 22.8.0 was released for 3.11.
