### ISSUE TITLE
Python 3.11 Alpine builds not installing Gevent with Unknown Type Name 'CFrame'

### ISSUE THREAD

**Issue by Yun-Kim** [gevent/gevent#1903]
### Description:
I tried installing gevent latest (21.12.0) through pip with Python 3.11, through alpine docker image and encountered a build error, while Python versions 3.10 + 3.9 + 3.7 did not have any problems through Docker alpine. For reference, here is my Dockerfile that I used to recreate this error:
```
# syntax=docker/dockerfile:1

FROM python:3.11-rc-alpine
RUN apk update && apk add python3-dev gcc libc-dev libffi-dev
RUN apk add build-base
RUN pip3 install gevent
```
This is the error I'm seeing:

```
#10 64.32       In file included from src/gevent/_greenlet_primitives.c:1050:
#10 64.32       /tmp/pip-install-f8ugc3sv/gevent_f5bed2c2b57c4666be99152f82ea72fa/deps/greenlet/greenlet.h:42:5: error: unknown type name 'CFrame'
#10 64.32          42 |     CFrame* cframe;
#10 64.32             |     ^~~~~~
#10 64.32       error: command '/usr/bin/gcc' failed with exit code 1
#10 64.32       [end of output]
```
Any help would be appreciated. Thank you!

**Comment by Behoston** [comment]
gevent currently does not support greenlet version 2.0.0 or higher. greenlet version 1.x.x does not work on Python 3.11 so you need wait for at least alpha support for Python 3.11 (or for greenlet >=2).

**Comment by jamadden** [comment]
Duplicate of #1902

**Comment by mbeijen** [comment]
greenlet 1.1.3 is now supporting Python 3.11
https://github.com/python-greenlet/greenlet/blob/maint/1.1/CHANGES.rst#113-2022-08-25

**Comment by sirodeneko** [comment]
@jamadden It still can't work
```
➜  mt_serving git:(master) pip3 list |grep -E  "greenlet|setuptools|zope.interface|zope.event"
greenlet       1.1.3.post0
setuptools     65.5.0
zope.event     4.5.0
zope.interface 5.5.1
➜  mt_serving git:(master) pip3 install gevent==21.12.0    
     ..........
      building 'gevent._gevent_c_greenlet_primitives' extension
      gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/python3.11/include/python3.11 -I/usr/local/python3.11/include/python3.11 -I/tmp/pip-install-81djr7da/gevent_3dbf37f879574097840ade2cede9370d/deps -Isrc/gevent -Isrc/gevent/libev -Isrc/gevent/resolver -I. -I/usr/local/python3.11/include/python3.11 -c src/gevent/_greenlet_primitives.c -o build/temp.linux-x86_64-cpython-311/src/gevent/_greenlet_primitives.o
      In file included from src/gevent/_greenlet_primitives.c:1050:
      /tmp/pip-install-81djr7da/gevent_3dbf37f879574097840ade2cede9370d/deps/greenlet/greenlet.h:42:5: error: unknown type name ‘CFrame’
           CFrame* cframe;
           ^~~~~~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gevent
Failed to build gevent
ERROR: Could not build wheels for gevent, which is required to install pyproject.toml-based projects
```

**Comment by jamadden** [comment]
You are still attempting to install versions that are too old. The first version of gevent that supports Python 3.11 is 22.08.0.
