### ISSUE TITLE
Removal of select.poll() breaks subprocess module.

### ISSUE THREAD

**Issue by GrahamDumpleton** [gevent/gevent#446]
I haven't encountered this directly, but have now had a couple of New Relic Python agent users raise the problem with us.

The problem is that in the Python subprocess module it has:

```
import select
_has_poll = hasattr(select, 'poll')
```

Thus _has_poll will only be true if poll() exists in the select module.

Later it has:

```
            if _has_poll:
                stdout, stderr = self._communicate_with_poll(input)
            else:
                stdout, stderr = self._communicate_with_select(input)
```

and then in _communicate_with_poll() it has:

```
poller = select.poll()
```

The problem is that in gevent monkey patching it will remove the poll() function from the select module.

```
def patch_select(aggressive=True):
    """Replace :func:`select.select` with :func:`gevent.select.select`.

    If aggressive is true (the default), also remove other blocking functions the :mod:`select`.
    """
    patch_module('select')
    if aggressive:
        select = __import__('select')
        # since these are blocking we're removing them here. This makes some other
        # modules (e.g. asyncore)  non-blocking, as they use select that we provide
        # when none of these are available.
        remove_item(select, 'poll')
        remove_item(select, 'epoll')
        remove_item(select, 'kqueue')
        remove_item(select, 'kevent')
```

The end result is that if the subprocess module had been imported prior to gevent doing any monkey patching, then gevent is breaking the subprocess module as it has cached that the poll() function existed.

You therefore get:

```
File "/usr/lib/python2.7/subprocess.py", line 799, in communicate return self._communicate(input)
File "/usr/lib/python2.7/subprocess.py", line 1401, in _communicate stdout, stderr = self._communicate_with_poll(input)
File "/usr/lib/python2.7/subprocess.py", line 1431, in _communicate_with_poll poller = select.poll()
AttributeError: 'module' object has no attribute 'poll'
```

If gevent is going to remove the poll() function, it should perhaps update the subprocess module and set _have_poll to False to avoid the problem.

One could argue gevent shouldn't need to consider that other modules have cached stuff from the select module, but since subprocess is part of the standard library, may be prudent to consider addressing the problem.

**Comment by imoonkey** [comment]
Seeing this when using gunicorn together when I have a package used subprocess.

Any fast workaround available???

**Comment by jamadden** [comment]
There are three possible workarounds described above:

1. Make sure to default monkey-patch before anything else imports subprocess. A good rule of thumb is to monkey patch in the first line of the first imported module.
2. Monkey-patch subprocess if it hasn't already been done.
3. As a last resort, if nothing can be monkey-patched, try setting `subprocess._has_poll` to `False` before using that module.

**Comment by imoonkey** [comment]
Thanks jamadden, I got this solved.

This might be kind of dumb. But if you also came across this error while using gunicorn, updating gunicorn to 19.0.5 or higher might simply solve this problem. I guess they might have done the monkey patching the right way in the newer version.

**Comment by jamadden** [comment]
The potential fix to `gevent.monkey` (altering `subprocess._has_poll` when patching the `select` module) will no longer work on Python 3.4+. This is because under 3.4, `subprocess` has been changed to use the new-in-3.4 `selectors` module, and gevent is not currently aware of that module at all. If `selectors` is imported first, then `select` is monkey patched, a non-monkey patched subprocess imported before or after the monkey patch will be broken if the platform natively supported `poll`.

It seems clear that gevent needs to learn about `selectors` if we want to support a mixed patched/non-patched environment. 

However, it's been a year since gunicorn started monkey-patching subprocess by default, and I'm not aware of any issue outstanding with that. Denis's remarks about not monkey-patching it by default because it's new probably are no longer valid. It seems reasonable to me that this should be changed in master/1.1. I'll open a PR for that.

**Comment by jamadden** [comment]
Closed by fc73e9afa34d811ede5d62531025d2e3876b8c01.

**Comment by FirefighterBlu3** [comment]
i bit disingenuous for aggressive to be the default to remove poll, kqueue etc :-/ there's plenty of valid reason for some software to use these functions whether select is monkey patched or not. instead of simply removing the function, it should be replaced with a function that raises an exception that explains that method foo() has been removed by monkey patching.

**Comment by jamadden** [comment]
@FirefighterBlu3 The non-`select` functions have availability that varies by platform already. Conforming  code generally needs to be prepared to fallback to `select` anyway. The `selectors` module in 3.4 is a good example of this pattern:
```python
if hasattr(select, 'poll'):
    class PollSelector:
       def __init__(self):
             self.poll = select.poll()

if 'PollSelector' in globals():
    DefaultSelector = PollSelector
else:
    DefaultSelector = SelectSelector
```

Replacing `poll`, etc, rather than removing them, breaks this common pattern.

**Comment by zeonglow** [comment]
If you are trying to be clever with the number of workers to CPU's in gunicorn_conf.py like this
```python
    from multiprocessing import cpu_count
    from gevent import monkey 
    monkey.patch_all()

    workers = 1
    try:
        workers = cpu_count() + 1
    except NotImplementedError:
        pass
```
Don't. Do this instead:
```python
     from gevent import monkey 
     monkey.patch_all()
     from multiprocessing import cpu_count
    ...
```
