### ISSUE TITLE
ssl broken for python > 2.7.9

### ISSUE THREAD

**Issue by joequant** [gevent/gevent#477]
https://github.com/eventlet/eventlet/issues/135

2.7.9 removed _sslwrap which means that the gevent ssl.py will fail.

**Comment by josegonzalez** [comment]
I had this same issue, but was able to correct it by adding @Eugeny's fix as a custom `ssl_279.py` module in my app and then importing it. Seems to fix my flask/gevent/gunicorn app at least.

**Comment by josegonzalez** [comment]
As @pigmej mentioned, the SSLSocket issue is still a problem. Here's the "bad" [code](https://github.com/gevent/gevent/blob/master/gevent/_ssl2.py#L58). I looked into the gevent code, don't know what the exact fix would be. Lame that this effects heroku apps :(

**Comment by mtsgrd** [comment]
@josegonzalez this hasn't affected our Heroku apps in my domain yet. Can you confirm you see it on Heroku?

As of yesterday, I now see this issue on Travis.

**Comment by josegonzalez** [comment]
I definitely saw this on heroku when I commented here last, so I downgraded my python to 2.7.8 to have it work.

**Comment by iElectric** [comment]
Debian has a patch: https://bazaar.launchpad.net/~ubuntu-branches/ubuntu/utopic/python-gevent/utopic/view/head:/debian/patches/sslwrap.py

**Comment by tomster** [comment]
@iElectric you sure that patch works? i applied it to gevent 1.0.1 and that results in ``NameError: global name 'SSLContext' is not defined`` when running the patched version. looking at the initial file i cannot see how that patch should fix the issue.

does anybody have a fix for this?

**Comment by iElectric** [comment]
Could you paste the whole traceback? Thanks!

**Comment by fdr** [comment]
This is breaking https://github.com/wal-e/wal-e tests, after I upgraded to Ubuntu 14.10 from 14.04. I haven't seen this reported in the wild from a user, though.

**Comment by iElectric** [comment]
@tomster https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/gevent_sslwrap.patch (also see above commit)

**Comment by iElectric** [comment]
@fdr wal-e is still failing due to boto: https://gist.github.com/ocharles/b1b53355b5bb2162871e

**Comment by itaykahana** [comment]
@pigmej I have the same issue with Heroku/Python 2.7.9/Gevent environment. Tried your patch, and also to change the SSLSocket constructor to accept `server_hostname` and `_context`.

I still have a problem with the self parameter.
In the original ssl.py file of python 2.7.9, line 346: the wrap_socket function of SSLContext returns `SSLSocket(self=self, sock=sock, server_side=server_side,
                         do_handshake_on_connect=do_handshake_on_connect,
                         suppress_ragged_eofs=suppress_ragged_eofs,
                         server_hostname=server_hostname,
                         _context=self)`

If I run this line with Gevent (and after fixing the signature of the constuctor) , I get: 
`TypeError: __init__() got multiple values for keyword argument 'self'`

Any advice?

**Comment by peterlundberg** [comment]
This is very important to find a sustainable solution for! 

Newer version of urllib3 (eg as used by requests 2.5.1) have behaviour checking for `SSLContext`as this implies different SSL support in python (as of 2.7.9 backport, previously). Thus just patching `sslwrap` (patch above works!) only helps code using that 'old' interface. `SSLSocket` constructor could perhaps also be patched, but in the long run this patching is a Bad idea (tm). 

Gevent needs to be written to support the new SSLContext interface to support SSL in python 2.7.9+. Is there any progess/plans/forks for this? It is very concerning that such a major problem does not have a solution after 6 months.

It is a deal-breaker for using python to get coroutine performance. What other options are there that can run in modern 2.7+ deployments?

**Comment by Microserf** [comment]
@itaykahana 

I've got Heroku/Python 2.7.9/Gevent running all together. I was able to do this by sourcing @jaredhobbs's forked & patched version [here](https://github.com/jaredhobbs/gevent#bd5885399152dcca7b1e949ee09f81098949250a), and including `Cython` as a requirement to enable its compilation.

It adds a solid 5-8 minutes to our build, and that sometimes pushes us over Heroku's 15 minutes deployment timeout, so it's not ideal, but it works.

**Comment by dsem** [comment]
[As of December 11th](https://devcenter.heroku.com/changelog-items/566), new Heroku apps use Python 2.7.9 (and suffer from this bug).  [Force 2.7.8](https://devcenter.heroku.com/articles/python-runtimes) with:

    echo 'python-2.7.8' > runtime.txt

**Comment by eeveeta** [comment]
+1
Modifying the constructor as @pigmej suggested worked for me.

**Comment by iElectric** [comment]
@denik there are a couple of solutions around here, any input?

**Comment by iElectric** [comment]
Seems like there is a lot to backport: https://github.com/python/cpython/commit/71a4ee3ea2c6847b9fc4b33cbc8d565a7bf2424a

**Comment by iElectric** [comment]
cc @alex

**Comment by parasyte** [comment]
I don't know about what else needs to be backported, but I ended up combining @Eugeny's original polyfill with one of my own for the `SSLSocket` constructor (as described by @pigmej)

https://gist.github.com/parasyte/27d72692efa74e23463b

**Comment by RonRothman** [comment]
@Eugeny and @parasyte, many thanks for your patches; worked for me.

**Comment by sprin** [comment]
A [bounty](https://www.bountysource.com/issues/5067076-wrap_socket-does-not-accept-server_hostname-in-2-7-x-breaks-with-gevent) was started on shazow/urllib3#482. There is some consensus that a patch to gevent would be the best solution, so I think a contributor to gevent would be very welcome to claim the bounty.

**Comment by sprin** [comment]
I think it is worth mentioning again for anyone who might grab one of the above patches without reading carefully the entire post that **hostname verification will not work**. At least, I was not able to use hostname verification with any of these patches, which is the default in recent versions of requests.

Hostname verification was one of the motivations for the backported SSL code in 2.7.9. Without it, man-in-the-middle attacks are trivial. This was assigned [CVE-2014-9365](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-9365) by request of [Alex Gaynor](http://www.openwall.com/lists/oss-security/2014/12/11/1).

I recommend reading both of those links before you decide to apply any of the above patches.

When I tried to use hostname verification with these patches using requests==2.6.0, I saw:
```
ValueError: empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED
```

**Comment by Ivoz** [comment]
Ya, I've been looking at and doing some work on this patch, but as sprin mentions the patch to 2.7.9 for ssl was a large one so this will be a large patch as well, it's not simply a couple of lines of adaptation.

**Comment by debunge** [comment]
@parasyte  where should I import your snippet? 

I'm trying 
```
import gevent_ssl
import gevent.monkey
gevent.monkey.patch_socket()
gevent.monkey.patch_ssl()
from gevent.pool import Pool
import requests
import gevent_ssl
```
but it seems I need to import your snippet from different place which I could not figure out.

**Comment by parasyte** [comment]
@debunge Import right after monkey.patch should be enough. Your example has it importing twice.

```python
import gevent.monkey
gevent.monkey.patch_socket()
gevent.monkey.patch_ssl()

import gevent_ssl

from gevent.pool import Pool
import requests
```

**Comment by debunge** [comment]
@parasyte thanks for swift replay, but for some reason this is not working.

I'm still getting the 
TypeError: __init__() got an unexpected keyword argument 'server_hostname'
<Greenlet at 0x7fda37b257d0: get_url(u'http://tmblr.co/ZBk6Cn1gZisvA')> failed with TypeError
 

The whole code is below

```
import gevent.monkey
gevent.monkey.patch_socket()
gevent.monkey.patch_ssl()

import gevent_ssl

from gevent.pool import Pool
import requests

def get_urls():
    pool = Pool(10)
    for url in db.urls.find({"original_url":None}):
        pool.spawn(get_url, url['_id'])
    pool.join()

def get_url(url):
    resp = requests.request('GET', url, timeout=5.0)
    if resp.ok:
       ...
        db.texts.save({'_id':url_normalized, 'text': remove_tags(s)})
        db.urls.update({'_id':url}, {'$set': {'original_url': url_normalized}})
    else:
        print resp

get_urls()
```

**Comment by parasyte** [comment]
The full stack trace would be more useful to troubleshooting, TBH. Also, the gevent_ssl monkey-patch is of limited use outside of Python 2.7.9 and gevent 1.0.1, so verify your installed versions: `python --version` and `pip freeze`

**Comment by debunge** [comment]
I have gevent 1.0.1 but my python version is 
```
python --version
Python 2.7.8
```

Here is a traceback 
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "downloader.py", line 38, in get_url
    resp = requests.request('GET', url, timeout=5.0)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 179, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 327, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 496, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 298, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 218, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/ssl_.py", line 124, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
TypeError: __init__() got an unexpected keyword argument 'server_hostname'
<Greenlet at 0x7f6472a32730: get_url(u'http://tmblr.co/ZBk6Cn1gZisvA')> failed with TypeError
```

and here is a full code which I'm trying to run https://gist.github.com/debunge/3bde836ececd37a7d113 (it is not so long, yet,I've decided to paste it as gist)

**Comment by illicium** [comment]
@sprin, I've modified @parasyte's polyfill to fix the hostname verification error:

    ValueError: empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED

https://gist.github.com/illicium/55a0a630c05a7ae85d64

This is a very quick hack which may be completely broken and insecure. No guarantees :)

**Comment by parasyte** [comment]
@debunge For Python 2.7.8, you can move this line outside of the condition body (remove the indentation) : https://gist.github.com/parasyte/27d72692efa74e23463b#file-gevent_ssl-py-L49 The condition only triggers on Python 2.7.9

@illicium :+1: copy-pasta fail. :laughing:

**Comment by noamgat** [comment]
I've tried several patches from this thread, they all seem to fail the following test :

``` python
from gevent.monkey import patch_all
patch_all()
import gevent_ssl
import requests
requests.get('https://www.google.com')
```

Different exceptions get thrown based on the patch used, but I haven't been able to get the request to work...

**Comment by debunge** [comment]
@parasyte I've updated my python to 2.7.9 and still getting 
```
TypeError: __init__() got an unexpected keyword argument 'server_hostname'
```

**Comment by debunge** [comment]
Ok, using pyenv and rolling back to 2.7.7 was a solution for me.

**Comment by tclancy** [comment]
Same `[SSL: CERTIFICATE_VERIFY_FAILED]` here.

**Comment by illicium** [comment]
@debunge @tclancy Perhaps your endpoint is using [SNI](http://en.wikipedia.org/wiki/Server_Name_Indication), which doesn't work out of the box on Python 2. If you're using requests, try [installing the pyOpenSSL and ndg-httpsclient packages](http://stackoverflow.com/a/18579484/3182989).

**Comment by catskul** [comment]
@zeevt, this fix looks to be specific to 2.7.9, other than the specific references to 2.7.9 in the code, is there anything that would prevent this from also fixing the same problem in 2.7.8?

**Comment by debunge** [comment]
@catskul  I suggest using pyenv and downgrading for specific scripts. Really solved the problem for me.

**Comment by sthzg** [comment]
After building gevent with the fix provided by @zeevt the exception is gone (thanks for the efforts). I am curious if anyone has experience running that fix for a few days or if there are thoughts about it by the maintainers.

**Comment by Microserf** [comment]
This may or may not help, but I found out yesterday that in my case, there was a second contributing cause to these kinds of errors.

If anyone is running python 2.7.9 on OS X 10.10.3, there's an issue where an important certificate (Equifax) is missing from the System Keychain. This might be a cause of certain `[SSL: CERTIFICATE_VERIFY_FAILED]` errors.

To fix:

1. [Download the missing certificate](https://www.geotrust.com/resources/root_certificates/certificates/Equifax_Secure_Certificate_Authority.pem)
2. Open Keychain (`/Applications/Utilities/Keychain.app`)
3. Drag the Equifax certificate from (1) into Keychain app, installing it in the `System` keychain
4. Authenticate using a sudo-worthy account
5. Uninstall & re-install OpenSSL, `brew uninstall --force openssl && brew install openssl`


This took me a good long while to track down the cause, so I'm posting it here in case it helps anyone else. For those who aren't running OS X 10.10.3, my apologies for the noise.

(More background information [here](https://github.com/Homebrew/homebrew/pull/38495) and [here](https://www.mail-archive.com/openssl-dev@openssl.org/msg38695.html))

**Comment by ml31415** [comment]
I took the debian patch and made a quickfix out of it. The debian patch is actually missing to fix the connect method, which also uses sslwrap, and it does not set up the verify method of the context manager, so certificate validation fails there. This patch also avoids the hacky inspect solutions as seen above. I saw the ongoing process to write some proper solution for this in #546 , so I probably won't file this as a pull request. For others looking for a quick fix of this solution, you might want to try this branch: https://github.com/ml31415/gevent/tree/python279ssl

**Comment by ozancaglayan** [comment]
I reverted the `sslwrap.py` patch in the official Ubuntu 15.04 repository and applied Eugeny's patch over it and it is now fixed.

**Comment by cbsmith** [comment]
Thrilled to see this closed. Can't wait for a release so we can put this one behind us.

**Comment by ramnes** [comment]
Finally. :+1:

**Comment by mengzhuo** [comment]
Please Release ASAP.
We had to lock our deploy bot to lock Python 2.7.8, however our IT guys eager to update Python to 2.7.9
Totally piss IT guys off these day :(

**Comment by ultrabug** [comment]
> Please Release ASAP.

Yes :+1: we distro packagers **need** a proper tag please (better than ad-hoc patch)

> Totally piss IT guys off these day :( 

And they're right : https://security.gentoo.org/glsa/201503-10 !

Plz consider releasing a new tag ASAP.

**Comment by jamadden** [comment]
@sprin @ivoz What do you think about the state of the 1.0.2 branch? I may have time to make a release in the next few days.

**Comment by ml31415** [comment]
@jmadden pls have a look at the suggestions for `socket.connect` in my patch, before releasing smth.

**Comment by cbsmith** [comment]
@ml31415 Man, in all the excitement, I failed to even check SSLSocket.connect().

I presume you are referring to this change? https://github.com/gevent/gevent/compare/master...ml31415:python279ssl#diff-117c9127922ead54983bc5b173701483L333

At first glance, it seems like this logic in SSLSocket.connect() is unnecessary. If SSLSocket.__init__() sets self._sslobj, then by the time you get to SSLSocket.connect() this is just redundant logic, no? I'll test this out later today, but can you save me trouble by explaining to me what I'm not getting?

**Comment by ml31415** [comment]
@cbsmith I agree that the code looks a bit redundant there. I suppose it is necessaray, so that the handshake can be done after init. Nevertheless, the code was there before and supposedly for a reason and well tested. So I just wanted to replace any call to `sslwrap` with minimal rewriting.

**Comment by cbsmith** [comment]
@ml31415 I grok it now. Seems like this should be a common method shared between __init__() and connect().

**Comment by abonhomme** [comment]
For anyone using `grequests` it's important to place the import of `gevent_ssl` file AFTER you import `grequests`.

```python
import grequests
import gevent_ssl
```
But that should be all you need to do.  I originally missed the [comment](https://github.com/gevent/gevent/issues/477#issuecomment-85229728) by @parasyte and thus wasted a ton of time.

**Comment by jamadden** [comment]
I've pushed a 1.0.2 release to PyPi. If anyone has a chance to test it and verify that it works in their configuration, the feedback would be much appreciated before making a wider announcement. Thank you!

**Comment by mtsgrd** [comment]
Thanks to everyone involved in addressing this issue! We are all grateful. @jamadden I've tested 1.0.2 with one of my project and it works like a charm.

**Comment by ultrabug** [comment]
:+1: Thanks a lot to all those who contributed and helped in resolving this issue. Will also get my co-workers to ack the fix on their side too.

FYI to any Gentoo Linux user watching, I've packaged and released it on portage !

**Comment by asieira** [comment]
I'm still getting an error while using `gevents` with `grequests` on Mac OS X Yosemite with the homebrew Python 2.7.9:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/grequests.py", line 71, in send
    self.url, **merged_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
TypeError: __init__() got an unexpected keyword argument 'server_hostname'
<Greenlet at 0x10f462870: <bound method AsyncRequest.send of <grequests.AsyncRequest object at 0x10f42ae50>>(stream=False)> failed with TypeError
```

**Comment by parasyte** [comment]
@asieira If I'm reading the code right, it looks like this was fixed in urllib3 starting with v1.10.1. Perhaps updating urllib3 will fix it?

**Comment by asieira** [comment]
Actually I think I have the latest version of `urllib3`:
```
| => pip freeze | grep urllib3
urllib3==1.10.4
| => yolk -U urllib3
You have the latest version installed.
```

**Comment by asieira** [comment]
I can confirm that the exact same application works on Amazon Linux with gevent 1.0.2, urllib3 1.10.4, grequests 0.2.0 and Python 2.7.9. So as strange as that may sound, it might be something specific to the Mac OS X homebrew Python 2.7.9 code.

**Comment by jamadden** [comment]
@asieira `requests` "vendors in" (provides its own copy of) the `urllib3` package. Unless you remove the `requests/packages/urllib3` directory, any separate urllib3 you have installed won't be used. 

That said, `requests` 2.7.0 vendors in `urllib3` 1.10.4, so the next question would be, what version of requests are you using?

It almost looks as if the monkey patching that `grequests` wants to do has been interrupted. This could be caused by a few things. It could also be that we're detecting the Python version incorrectly and choosing the wrong SSL implementation. If you start up an interactive Python interpreter and monkey-patch manually, what do you see? If things are working correctly, you should see something like this:

```python
>>> import gevent.monkey; gevent.monkey.patch_all()
>>> import ssl
>>> ssl.SSLContext
<class 'gevent._sslgte279.SSLContext'>
>>> ssl.SSLSocket
<class 'gevent._sslgte279.SSLSocket'>
>>> import sys
>>> print(sys.version)
>>> print( sys.version )
2.7.9 (default, Dec 13 2014, 15:13:49)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
```

The `_sslgte279` is the key, showing that we're using the SSL module that was built to match `sys.version`.

**Comment by asieira** [comment]
First, the package versions you asked about seem to be correct:
```
| => pip freeze | grep requests
grequests==0.2.0
requests==2.7.0
```
And this is the output I get running your sample code on my Python interpreter:
```
| => python
Python 2.7.9 (default, May  1 2015, 19:04:44) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent.monkey; gevent.monkey.patch_all()
>>> import ssl
>>> ssl.SSLContext
<class 'gevent._sslgte279.SSLContext'>
>>> ssl.SSLSocket
<class 'gevent._sslgte279.SSLSocket'>
>>> import sys
>>> print(sys.version)
2.7.9 (default, May  1 2015, 19:04:44) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)]
```

So again, everything seems to be in order. :(

**Comment by asieira** [comment]
Wait, I reinstalled Python and for some reason it is now working. Go figure. :)

Thank you all for your help.

**Comment by jamadden** [comment]
Thanks for the feedback everyone. We've gone ahead and announced the release.

**Comment by shazow** [comment]
FYI there's a $130 bounty on urllib3 for what I believe was this bug, who would be the appropriate person to claim it? https://www.bountysource.com/issues/5067076-wrap_socket-does-not-accept-server_hostname-in-2-7-x-breaks-with-gevent

**Comment by jamadden** [comment]
@sprin did the initial port, although there were several others involved in backporting from master to 1.0.x and reviewing and testing such as @Ivoz and @thedrow.

**Comment by shazow** [comment]
If one of you would like to submit a claim on Bountysource, I think you can describe the appropriate split and ask them to distribute the bounty accordingly. :) (Might need to send an email once a claim has been submitted.) Let me know if I can help!

**Comment by jasonwiener** [comment]
Thanks you guys! Really helped me out!

**Comment by transfluxus** [comment]
I'm using python 2.7.10 and gevent 1.0.1
when I try to upgrade gevent it fails  
error: command 'cc' failed with exit status 1
