### ISSUE TITLE
gevent: 25.5.1  'gevent._gevent_cqueue.Queue' object has no attribute 'Empty'

### ISSUE THREAD

**Issue by pay748** [gevent/gevent#2113]
After upgrading gevent from 24.11.1 to 25.5.1, the built-in queue library in the system will display the error 'gevent._gevent_cqueue.Queue' object has no attribute 'Empty' when calling q.Empty after monkey patching.

The following is the code example, and the running results of using gevent 24.11.1 and gevent 25.5.1 on the same computer respectively

```python
# minimal reproducer
import platform
import sys

import gevent
import queue
from gevent import monkey

monkey.patch_all()


def create_queue(*args, **kwargs):
    q = queue.Queue(*args, **kwargs)
    q.Empty = queue.Empty


if __name__ == "__main__":
    print(f"Python: {sys.version}")
    print(f"gevent: {gevent.__version__}")
    print(f"os: {platform.system()} {platform.release()} {platform.machine()}")
    create_queue()
```

**gevent 24.11.1** 

> ....\python.exe ...\queue\gevent_test.py
> Python: 3.13.2 (tags/v3.13.2:4f8bb39, Feb  4 2025, 15:23:48) [MSC v.1942 64 bit (AMD64)]
> gevent: 24.11.1
> os: Windows 11 AMD64

**gevent 25.5.1** 

> Python: 3.13.2 (tags/v3.13.2:4f8bb39, Feb  4 2025, 15:23:48) [MSC v.1942 64 bit (AMD64)]
> gevent: 25.5.1
> os: Windows 11 AMD64
> Traceback (most recent call last):
>   File "...\queue\gevent_test.py", line 20, in <module>
>     create_queue()
>     ~~~~~~~~~~~~^^
>   File "...\queue\gevent_test.py", line 13, in create_queue
>     q.Empty = queue.Empty
>     ^^^^^^^
> AttributeError: 'gevent._gevent_cqueue.Queue' object has no attribute 'Empty' and no __dict__ for setting new attributes. Did you mean: 'empty'?
