### ISSUE TITLE
gevent fails to build with Cython 3.0.10

### ISSUE THREAD

**Issue by stratakis** [gevent/gevent#2031]
Hi,

I'm currently testing on Fedora a rebase of Cython from 3.0.9 to 3.0.10 and gevent fails to compile. I've tested both 23.9.1 and 24.2.1.

Error:
```
src/gevent/queue.c: In function ‘__pyx_pf_6gevent_14_gevent_cqueue_12UnboundQueue_2put’:
src/gevent/queue.c:11895:83: error: passing argument 1 of ‘__pyx_vtabptr_6gevent_14_gevent_cqueue_UnboundQueue->__pyx_base.put’ from incompatible pointer type [-Wincompatible-pointer-types]
11895 |   __pyx_t_1 = __pyx_vtabptr_6gevent_14_gevent_cqueue_UnboundQueue->__pyx_base.put(__pyx_v_self, __pyx_v_item, 1, &__pyx_t_2); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 432, __pyx_L1_error)
      |                                                                                   ^~~~~~~~~~~~
      |                                                                                   |
      |                                                                                   struct __pyx_obj_6gevent_14_gevent_cqueue_UnboundQueue *
src/gevent/queue.c:11895:83: note: expected ‘struct __pyx_obj_6gevent_14_gevent_cqueue_Queue *’ but argument is of type ‘struct __pyx_obj_6gevent_14_gevent_cqueue_UnboundQueue *’
src/gevent/queue.c:11895:114: error: passing argument 4 of ‘__pyx_vtabptr_6gevent_14_gevent_cqueue_UnboundQueue->__pyx_base.put’ from incompatible pointer type [-Wincompatible-pointer-types]
11895 |   __pyx_t_1 = __pyx_vtabptr_6gevent_14_gevent_cqueue_UnboundQueue->__pyx_base.put(__pyx_v_self, __pyx_v_item, 1, &__pyx_t_2); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 432, __pyx_L1_error)
      |                                                                                                                  ^~~~~~~~~~
      |                                                                                                        
      |
      |                                                                                                                  struct __pyx_opt_args_6gevent_14_gevent_cqueue_12UnboundQueue_put *
src/gevent/queue.c:11895:114: note: expected ‘struct __pyx_opt_args_6gevent_14_gevent_cqueue_5Queue_put *’ but argument is of type ‘struct __pyx_opt_args_6gevent_14_gevent_cqueue_12UnboundQueue_put *’
src/gevent/queue.c: At top level:
src/gevent/queue.c:7636:12: warning: ‘__pyx_pw_6gevent_14_gevent_cqueue_5Queue_25__nonzero__’ defined but not used [-Wunused-function]
 7636 | static int __pyx_pw_6gevent_14_gevent_cqueue_5Queue_25__nonzero__(PyObject *__pyx_v_self) {
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Full build log attached.

[builder-live.log](https://github.com/gevent/gevent/files/15101594/builder-live.log)

**Comment by hroncok** [comment]
Isn't this a Cython problem related to https://github.com/cython/cython/pull/6085 ?

**Comment by stratakis** [comment]
Indeed I've managed to workaround the issue by using this patch according to https://github.com/cython/cython/pull/6085#issuecomment-2077446195

```
--- a/src/gevent/_gevent_cqueue.pxd
+++ b/src/gevent/_gevent_cqueue.pxd
@@ -75,7 +75,6 @@ cdef class ItemWaiter(Waiter):
     cdef readonly Queue queue
 
 
-@cython.final
 cdef class UnboundQueue(Queue):
     pass
```

**Comment by glaubitz** [comment]
This is the same as #2028, it seems.

**Comment by jamadden** [comment]
The next version of gevent requires Cython 3.0.11 to build from source, which should fix this issue.
