### ISSUE TITLE
AttributeError: '_io.TextIOWrapper' object has no attribute 'readinto'

### ISSUE THREAD

**Issue by dmrlawson** [gevent/gevent#1542]
* gevent version: 1.5a3
* Python version: cpython 3.7.5, 3.8.2
* Operating System: Kubuntu 19.10, Ubuntu 18.04

### Description:

 Trying to do:

```python
$ python
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import gevent.fileobject
>>> gevent.fileobject.FileObjectThread(sys.stdin).readline()
Traceback (most recent call last):
  File "/home/davidlawson/virtualenvs/scrapers_37/lib/python3.7/site-packages/gevent/threadpool.py", line 120, in __run_task
    thread_result.set(func(*args, **kwargs))
AttributeError: '_io.TextIOWrapper' object has no attribute 'readinto'
2020-03-10T13:35:10Z (<ThreadPoolWorker at 0x7ffba1fb1ec0 thread_ident=0x7ffba1f87700 hub=<Hub at 0x7ffba21997d0 thread_ident=0x7ffba2de9740>>, <built-in method readline of _io.TextIOWrapper object at 0x7ffba24ce910>) failed with AttributeError

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/davidlawson/virtualenvs/scrapers_37/lib/python3.7/site-packages/gevent/_fileobjectcommon.py", line 525, in thread_method
    return threadpool.apply(method, args, kwargs)
  File "/home/davidlawson/virtualenvs/scrapers_37/lib/python3.7/site-packages/gevent/pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 279, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 307, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 297, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 277, in gevent._event.AsyncResult._raise_exception
  File "/home/davidlawson/virtualenvs/scrapers_37/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
    raise value.with_traceback(tb)
  File "/home/davidlawson/virtualenvs/scrapers_37/lib/python3.7/site-packages/gevent/threadpool.py", line 120, in __run_task
    thread_result.set(func(*args, **kwargs))
AttributeError: '_io.TextIOWrapper' object has no attribute 'readinto'
```

This works fine in gevent 1.5a2:

```python
$ python
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import gevent.fileobject
>>> gevent.fileobject.FileObjectThread(sys.stdin).readline()
Test input
'Test input\n'
```

I'm not sure where to look however

**Comment by dmrlawson** [comment]
I read `CHANGES.rst` which seemed to suggest I should be doing something like this:

```
>>> import gevent.fileobject, sys
>>> gevent.fileobject.FileObjectThread(sys.stdin, 'rb').readline()
Traceback (most recent call last):
  File "/home/davidlawson/virtualenvs/scrapers_37/lib/python3.7/site-packages/gevent/threadpool.py", line 120, in __run_task
    thread_result.set(func(*args, **kwargs))
AttributeError: '_io.TextIOWrapper' object has no attribute 'readinto'
2020-03-10T13:54:28Z (<ThreadPoolWorker at 0x7fd954054e10 thread_ident=0x7fd95402a700 hub=<Hub at 0x7fd95423c7d0 thread_ident=0x7fd954e8c740>>, <built-in method readline of _io.BufferedReader object at 0x7fd95402b4d0>) failed with AttributeError

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/davidlawson/virtualenvs/scrapers_37/lib/python3.7/site-packages/gevent/_fileobjectcommon.py", line 525, in thread_method
    return threadpool.apply(method, args, kwargs)
  File "/home/davidlawson/virtualenvs/scrapers_37/lib/python3.7/site-packages/gevent/pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 279, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 307, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 297, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 277, in gevent._event.AsyncResult._raise_exception
  File "/home/davidlawson/virtualenvs/scrapers_37/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
    raise value.with_traceback(tb)
  File "/home/davidlawson/virtualenvs/scrapers_37/lib/python3.7/site-packages/gevent/threadpool.py", line 120, in __run_task
    thread_result.set(func(*args, **kwargs))
AttributeError: '_io.TextIOWrapper' object has no attribute 'readinto'
```

but as you can see I get the same error

**Comment by dmrlawson** [comment]
I figured out that this works:

```python
>>> import gevent.fileobject, sys
>>> gevent.fileobject.FileObjectThread(sys.stdin, 'rb', buffering=0).readline()
Foo
'Foo\n'
>>> 
```

but I still think there's possibly a bug here?

**Comment by jamadden** [comment]
I agree, something isn’t right. Thanks for the report!
