### ISSUE TITLE
gevent does not compile in Python 2.5 virtualenv

### ISSUE THREAD

**Issue by denik** [gevent/gevent#78]
<b>What steps will reproduce the problem?</b>
1. Create Python 2.5 virtualenv
2. Activate the virtualenv
3. Install gevent with 'python setup.py install'

<b>What is the expected output? What do you see instead?</b>

It did compile in the past for me under Python 2.5 so it's either a regression in gevent or has to do with my environment.

Output of 'python setup.py install':

running install
running bdist_egg
running egg_info
writing requirements to gevent.egg-info/requires.txt
writing gevent.egg-info/PKG-INFO
writing top-level names to gevent.egg-info/top_level.txt
writing dependency_links to gevent.egg-info/dependency_links.txt
reading manifest file 'gevent.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'gevent.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
running build_py
running build_ext
building 'gevent.core' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.5 -c gevent/core.c -o build/temp.linux-i686-2.5/gevent/core.o
gevent/core.c: In function ‘__pyx_f_6gevent_4core_5event__addref’:
gevent/core.c:1878:5: warning: dereferencing ‘void *’ pointer
gevent/core.c:1878:5: error: request for member ‘ob_refcnt’ in something not a structure or union
gevent/core.c: In function ‘__pyx_f_6gevent_4core_5event__delref’:
gevent/core.c:1928:5: warning: dereferencing ‘void *’ pointer
gevent/core.c:1928:5: error: request for member ‘ob_refcnt’ in something not a structure or union
gevent/core.c: In function ‘__pyx_f_6gevent_4core___evdns_callback’:
gevent/core.c:6064:3: warning: dereferencing ‘void *’ pointer
gevent/core.c:6064:3: error: request for member ‘ob_refcnt’ in something not a structure or union
gevent/core.c: In function ‘__pyx_pf_6gevent_4core_10dns_resolve_ipv4’:
gevent/core.c:6540:3: warning: dereferencing ‘void *’ pointer
gevent/core.c:6540:3: error: request for member ‘ob_refcnt’ in something not a structure or union
gevent/core.c: In function ‘__pyx_pf_6gevent_4core_11dns_resolve_ipv6’:
gevent/core.c:6698:3: warning: dereferencing ‘void *’ pointer
gevent/core.c:6698:3: error: request for member ‘ob_refcnt’ in something not a structure or union
gevent/core.c: In function ‘__pyx_pf_6gevent_4core_12dns_resolve_reverse’:
gevent/core.c:6856:3: warning: dereferencing ‘void *’ pointer
gevent/core.c:6856:3: error: request for member ‘ob_refcnt’ in something not a structure or union
gevent/core.c: In function ‘__pyx_pf_6gevent_4core_13dns_resolve_reverse_ipv6’:
gevent/core.c:7011:3: warning: dereferencing ‘void *’ pointer
gevent/core.c:7011:3: error: request for member ‘ob_refcnt’ in something not a structure or union
gevent/core.c: In function ‘__pyx_f_6gevent_4core_19http_request_client__addref’:
gevent/core.c:12922:5: warning: dereferencing ‘void *’ pointer
gevent/core.c:12922:5: error: request for member ‘ob_refcnt’ in something not a structure or union
gevent/core.c: In function ‘__pyx_f_6gevent_4core_19http_request_client__delref’:
gevent/core.c:12972:5: warning: dereferencing ‘void *’ pointer
gevent/core.c:12972:5: error: request for member ‘ob_refcnt’ in something not a structure or union
gevent/core.c: In function ‘__pyx_pf_6gevent_4core_14set_exc_info’:
gevent/core.c:16277:5: warning: dereferencing ‘void *’ pointer
gevent/core.c:16277:5: error: request for member ‘ob_refcnt’ in something not a structure or union
gevent/core.c:16286:5: warning: dereferencing ‘void *’ pointer
gevent/core.c:16286:5: error: request for member ‘ob_refcnt’ in something not a structure or union
error: command 'gcc' failed with exit status 1

<b>What version of the gevent are you using?</b>

0.13.4

<b>What version of libevent are you using?</b>

2.0.10

<b>On what operating system?</b>

Archlinux i686

<b>On what Python?</b>

2.5.5

gcc version: 4.5.2<p><a href="http://code.google.com/p/gevent/issues/detail?id=78">Reported by michael@mseiwald.at.</a></p><hr/><h2>earlier comments</h2>

<p><strong>Denis.Bilenko said, at 2011-04-21T16:44:52.000Z:</strong></p>

<p>Thanks, fixed in https://bitbucket.org/denis/gevent-0.13/changeset/582c0c1ae1f1</p>
