### ISSUE TITLE
Cannot import gevent.event.Timeout with 1.3.0

### ISSUE THREAD

**Issue by dan-blanchard** [gevent/gevent#1205]
* gevent version: 1.3.0
* Python version: Python 3.6.4 downloaded from python.org
* Operating System: macOS 10.13.4 (but also seen on Travis running precise)

### Description:

Trying to import `gevent.event.Timeout` results in an `AttributeError`. This worked fine on `gevent` 1.2.2.

### What I've run:

```pytb
>>> import gevent.event
>>> gevent.event.Timeout
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gevent._event' has no attribute 'Timeout'
```

**Comment by jamadden** [comment]
Thanks!

As a workaround (for this specific issue in this specific release, I don't recommend this in general) if you set the `PURE_PYTHON` environment variable before importing gevent, some of the implementation details will be more like they were in 1.2.2---in particular this import will work. Naturally avoiding the extension modules slows things down, but it could be useful under dire circumstances.
